/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, PerspectiveCamera, OrbitControls } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane003: THREE.Mesh
    volume_shrinkwrap: THREE.Mesh
    ['0_Wind_Sail_00']: THREE.Mesh
    ['0_Wind_Sail_01']: THREE.Mesh
    ['0_Wind_Sail_02']: THREE.Mesh
    ['0_Wind_Sail_03']: THREE.Mesh
    ['0_Wind_Sail_04']: THREE.Mesh
    ['0_Wind_Sail_05']: THREE.Mesh
    ['0_Wind_Sail_06']: THREE.Mesh
    ['0_Wind_Sail_07']: THREE.Mesh
    ['0_Wind_Sail_08']: THREE.Mesh
    ['0_Wind_Sail_09']: THREE.Mesh
    ['0_Wind_Sail_10']: THREE.Mesh
    ['0_Wind_Sail_11']: THREE.Mesh
    ['0_Wind_Sail_12']: THREE.Mesh
    ['0_Wind_Sail_13']: THREE.Mesh
    ['0_Wind_Sail_14']: THREE.Mesh
    ['0_Wind_Sail_15']: THREE.Mesh
    ['2_big_00']: THREE.Mesh
    ['2_big_01']: THREE.Mesh
    ['2_big_01a']: THREE.Mesh
    ['2_big_02']: THREE.Mesh
    ['2_big_03']: THREE.Mesh
    ['2_big_04']: THREE.Mesh
    ['2_big_05']: THREE.Mesh
    ['2_big_06']: THREE.Mesh
    ['2_big_07']: THREE.Mesh
    ['2_big_08']: THREE.Mesh
    ['2_big_09']: THREE.Mesh
    ['2_big_09a']: THREE.Mesh
    ['2_big_09B']: THREE.Mesh
    ['2_big_10']: THREE.Mesh
    ['2_big_11']: THREE.Mesh
    ['2_big_11a']: THREE.Mesh
    ['2_big_11b']: THREE.Mesh
    ['2_boat_02']: THREE.Mesh
    ['2_boat_03']: THREE.Mesh
    ['2_boat_04']: THREE.Mesh
    ['2_boat_05']: THREE.Mesh
    ['2_boat_07']: THREE.Mesh
    ['2_boat_08']: THREE.Mesh
    ['2_boat_09']: THREE.Mesh
    ['2_boat_10']: THREE.Mesh
    ['2_boat_11']: THREE.Mesh
    ['2_boat_12']: THREE.Mesh
    ['2_boat_13']: THREE.Mesh
    ['2_boat_14']: THREE.Mesh
    ['2_boat_15']: THREE.Mesh
    ['2_boat_16']: THREE.Mesh
    ['2_boat_17']: THREE.Mesh
    ['2_boat_18']: THREE.Mesh
    ['2_boat_19']: THREE.Mesh
    ['2_boat_20']: THREE.Mesh
    ['2_cannon_00']: THREE.Mesh
    ['2_cannon_01']: THREE.Mesh
    ['2_cannon_02']: THREE.Mesh
    ['2_cannon_03']: THREE.Mesh
    ['2_cannon_04_Detached01']: THREE.Mesh
    ['2_cannon_04_Detached02']: THREE.Mesh
    ['2_cannon_04_Detached03']: THREE.Mesh
    ['2_cannon_04_Detached04']: THREE.Mesh
    ['2_cannon_04_Detached05']: THREE.Mesh
    ['2_cannon_04_Detached06']: THREE.Mesh
    ['2_cannon_04_Detached07']: THREE.Mesh
    ['2_cannon_04_Detached08']: THREE.Mesh
    ['2_cannon_04_Detached09']: THREE.Mesh
    ['2_cannon_04_Detached10']: THREE.Mesh
    ['2_cannon_04_Detached11']: THREE.Mesh
    ['2_cannon_04_Detached12']: THREE.Mesh
    ['2_cannon_04_Detached13']: THREE.Mesh
    ['2_cannon_04_Detached14']: THREE.Mesh
    ['2_cannon_04_Detached15']: THREE.Mesh
    ['2_cannon_04_Detached16']: THREE.Mesh
    ['2_cannon_04_Detached17']: THREE.Mesh
    ['2_cannon_04_Detached18']: THREE.Mesh
    ['2_cannon_04_Detached19']: THREE.Mesh
    ['2_cannon_04_Detached20']: THREE.Mesh
    ['2_cannon_04_Detached21']: THREE.Mesh
    ['2_cannon_04_Detached22']: THREE.Mesh
    ['2_cannon_04_Detached23']: THREE.Mesh
    ['2_cannon_04_Detached24']: THREE.Mesh
    ['2_cannon_04_Detached25']: THREE.Mesh
    ['2_cannon_04_Detached26']: THREE.Mesh
    ['2_cannon_04_Detached27']: THREE.Mesh
    ['2_cannon_04_Detached28']: THREE.Mesh
    ['2_cannon_04_Detached29']: THREE.Mesh
    ['2_cannon_04_Detached30']: THREE.Mesh
    ['2_cannon_04_Detached31']: THREE.Mesh
    ['2_cannon_04_Detached32']: THREE.Mesh
    ['2_cannon_05']: THREE.Mesh
    ['2_cannon_smo_00']: THREE.Mesh
    ['2_cannon_smo_01']: THREE.Mesh
    ['2_cannon_smo_02']: THREE.Mesh
    ['2_cannon_smo_03']: THREE.Mesh
    ['2_cannon_smo_04']: THREE.Mesh
    ['2_cannon_smo_05']: THREE.Mesh
    ['2_center_00']: THREE.Mesh
    ['2_center_01']: THREE.Mesh
    ['2_center_03']: THREE.Mesh
    ['2_center_04']: THREE.Mesh
    ['2_center_05']: THREE.Mesh
    ['2_center_08']: THREE.Mesh
    ['2_center_09']: THREE.Mesh
    ['2_center_10']: THREE.Mesh
    ['2_center_11']: THREE.Mesh
    ['2_center_12']: THREE.Mesh
    ['2_center_13']: THREE.Mesh
    ['2_center_14']: THREE.Mesh
    ['2_center_15']: THREE.Mesh
    ['2_center_16']: THREE.Mesh
    ['2_center_17']: THREE.Mesh
    ['2_center_18']: THREE.Mesh
    ['2_center_19']: THREE.Mesh
    ['2_center_20']: THREE.Mesh
    ['2_center_21']: THREE.Mesh
    ['2_center_22']: THREE.Mesh
    ['2_center_23']: THREE.Mesh
    ['2_center_24']: THREE.Mesh
    ['2_center_25']: THREE.Mesh
    ['2_center_26']: THREE.Mesh
    ['2_center_27']: THREE.Mesh
    ['2_center_28']: THREE.Mesh
    ['2_figurehead_00']: THREE.Mesh
    ['2_figurehead_01']: THREE.Mesh
    ['2_figurehead_02']: THREE.Mesh
    ['2_figurehead_03']: THREE.Mesh
    ['2_figurehead_04']: THREE.Mesh
    ['2_figurehead_05']: THREE.Mesh
    ['2_figurehead_06']: THREE.Mesh
    ['2_front_00']: THREE.Mesh
    ['2_front_01']: THREE.Mesh
    ['2_front_02']: THREE.Mesh
    ['2_front_04']: THREE.Mesh
    ['2_front_05']: THREE.Mesh
    ['2_front_06']: THREE.Mesh
    ['2_inside_00']: THREE.Mesh
    ['2_inside_01']: THREE.Mesh
    ['2_inside_02']: THREE.Mesh
    ['2_inside_03']: THREE.Mesh
    ['2_mast_01']: THREE.Mesh
    ['2_mast_02']: THREE.Mesh
    ['2_mast_03']: THREE.Mesh
    ['2_mast_04']: THREE.Mesh
    ['2_mast_36']: THREE.Mesh
    ['2_mast_44']: THREE.Mesh
    ['2_mast_05']: THREE.Mesh
    ['2_mast_06']: THREE.Mesh
    ['2_mast_35']: THREE.Mesh
    ['2_mast_43']: THREE.Mesh
    ['2_mast_07']: THREE.Mesh
    ['2_mast_08']: THREE.Mesh
    ['2_mast_09']: THREE.Mesh
    ['2_mast_33']: THREE.Mesh
    ['2_mast_38']: THREE.Mesh
    ['2_mast_46']: THREE.Mesh
    ['2_mast_39']: THREE.Mesh
    ['2_mast_40']: THREE.Mesh
    ['2_mast_41']: THREE.Mesh
    ['2_mast_47']: THREE.Mesh
    ['2_mast_48']: THREE.Mesh
    ['2_mast_49']: THREE.Mesh
    ['2_name_01']: THREE.Mesh
    ['2_name_02']: THREE.Mesh
    ['2_Rig_Smo_00']: THREE.Mesh
    ['2_Rig_Smo_15']: THREE.Mesh
    ['2_Rig_Smo_23']: THREE.Mesh
    ['2_Rig_Smo_01']: THREE.Mesh
    ['2_Rig_Smo_22']: THREE.Mesh
    ['2_Rig_Smo_02']: THREE.Mesh
    ['2_Rig_Smo_03']: THREE.Mesh
    ['2_Rig_Smo_04']: THREE.Mesh
    ['2_Rig_Smo_05']: THREE.Mesh
    ['2_Rig_Smo_06']: THREE.Mesh
    ['2_Rig_Smo_09']: THREE.Mesh
    ['2_Rig_Smo_17']: THREE.Mesh
    ['2_Rig_Smo_07']: THREE.Mesh
    ['2_Rig_Smo_08']: THREE.Mesh
    ['2_Rig_Smo_10']: THREE.Mesh
    ['2_Rig_Smo_11']: THREE.Mesh
    ['2_Rig_Smo_12']: THREE.Mesh
    ['2_Rig_Smo_13']: THREE.Mesh
    ['2_Rig_Smo_14']: THREE.Mesh
    ['2_Rig_Smo_16']: THREE.Mesh
    ['2_Rig_Smo_16001']: THREE.Mesh
    ['2_Rig_Smo_16a']: THREE.Mesh
    ['2_Rig_Smo_18']: THREE.Mesh
    ['2_Rig_Smo_19']: THREE.Mesh
    ['2_Rig_Smo_20']: THREE.Mesh
    ['2_Rig_Smo_21']: THREE.Mesh
    ['2_ship_smooth_big_00']: THREE.Mesh
    ['2_ship_smooth_big_01']: THREE.Mesh
    ['2_ship_smooth_big_02']: THREE.Mesh
    ['2_ship_smooth_big_03']: THREE.Mesh
    ['2_ship_smooth_big_04']: THREE.Mesh
    ['2_ship_smooth_big_05']: THREE.Mesh
    ['2_sides_01']: THREE.Mesh
    ['2_sides_02']: THREE.Mesh
    ['2_sides_03']: THREE.Mesh
    ['2_sides_04']: THREE.Mesh
    ['2_sides_05']: THREE.Mesh
    ['2_sides_06']: THREE.Mesh
    ['2_sides_07']: THREE.Mesh
    ['2_sides_08']: THREE.Mesh
    ['2_sides_09']: THREE.Mesh
    ['2_sides_10']: THREE.Mesh
    ['2_sides_11']: THREE.Mesh
    ['2_sides_12']: THREE.Mesh
    ['2_sides_13']: THREE.Mesh
    ['2_sides_14']: THREE.Mesh
    ['2_sides_15']: THREE.Mesh
    ['2_Stern_00']: THREE.Mesh
    ['2_Stern_01']: THREE.Mesh
    ['2_Stern_02']: THREE.Mesh
    ['2_Stern_03']: THREE.Mesh
    ['2_Stern_04']: THREE.Mesh
    ['2_Stern_05']: THREE.Mesh
    ['2_Stern_06']: THREE.Mesh
    ['2_Stern_07']: THREE.Mesh
    ['2_Stern_08']: THREE.Mesh
    ['2_Stern_09']: THREE.Mesh
    ['2_Stern_10']: THREE.Mesh
    ['2_Stern_11']: THREE.Mesh
    NoWind_Sail_Rig_00: THREE.Mesh
    NoWind_Sail_Rig_11: THREE.Mesh
    NoWind_Sail_Rig_12: THREE.Mesh
    NoWind_Sail_Rig_13: THREE.Mesh
    NoWind_Sail_Rig_14: THREE.Mesh
    NoWind_Sail_Rig_15: THREE.Mesh
    NoWind_Sail_Rig_16: THREE.Mesh
    NoWind_Sail_Rig_20: THREE.Mesh
    NoWind_Sail_Rig_21: THREE.Mesh
    NoWind_Sail_Rig_22: THREE.Mesh
    NoWind_Sail_Rig_23: THREE.Mesh
    NoWind_Sail_Rig_24: THREE.Mesh
    NoWind_Sail_Rig_25: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {
    Sail_Cloth: THREE.MeshPhysicalMaterial
    yellow_wood__with_normal: THREE.MeshPhysicalMaterial
    black_wood: THREE.MeshPhysicalMaterial
    wood_floor: THREE.MeshPhysicalMaterial
    yellow_wood_clean: THREE.MeshPhysicalMaterial
    black_paint1: THREE.MeshPhysicalMaterial
    white_board_bare: THREE.MeshPhysicalMaterial
    white_board: THREE.MeshPhysicalMaterial
    green_board: THREE.MeshPhysicalMaterial
    pale_wood2: THREE.MeshPhysicalMaterial
    rope: THREE.MeshPhysicalMaterial
    rope_darker: THREE.MeshPhysicalMaterial
    wood_dark_red_shiny: THREE.MeshPhysicalMaterial
    mesh: THREE.MeshPhysicalMaterial
    black_fabric: THREE.MeshPhysicalMaterial
    keg: THREE.MeshPhysicalMaterial
    red_wood: THREE.MeshPhysicalMaterial
    Glass: THREE.MeshPhysicalMaterial
    wood_dark_brown: THREE.MeshPhysicalMaterial
    wood_mahogney: THREE.MeshPhysicalMaterial
    white: THREE.MeshPhysicalMaterial
    fake_fab_red: THREE.MeshPhysicalMaterial
    blue_fab: THREE.MeshPhysicalMaterial
    shield: THREE.MeshPhysicalMaterial
    Gold_disturbed: THREE.MeshPhysicalMaterial
    Material__211: THREE.MeshPhysicalMaterial
    blue: THREE.MeshPhysicalMaterial
    flag3: THREE.MeshPhysicalMaterial
    flag1: THREE.MeshPhysicalMaterial
    flag2: THREE.MeshPhysicalMaterial
    NAME1: THREE.MeshPhysicalMaterial
    NAME2: THREE.MeshPhysicalMaterial
    door: THREE.MeshPhysicalMaterial
    gate: THREE.MeshPhysicalMaterial
    red_wood_clean: THREE.MeshPhysicalMaterial
    stern_deco_a: THREE.MeshPhysicalMaterial
    LOD_Lamp: THREE.MeshPhysicalMaterial
    LOD_Win_Deco: THREE.MeshPhysicalMaterial
    LOD_Win: THREE.MeshPhysicalMaterial
    deco1: THREE.MeshPhysicalMaterial
    LOD_back__deco: THREE.MeshPhysicalMaterial
    LOD_side_deco_trans: THREE.MeshPhysicalMaterial
    ocean: THREE.MeshPhysicalMaterial
  }
}

type ActionName =
  | 'KeyAction'
  | '0_Wind_Sail_00Action.001'
  | '0_Wind_Sail_01Action.001'
  | '0_Wind_Sail_02Action.001'
  | '0_Wind_Sail_03Action.001'
  | '0_Wind_Sail_04Action.001'
  | '0_Wind_Sail_05Action.001'
  | '0_Wind_Sail_06Action.001'
  | '0_Wind_Sail_07Action.001'
  | '0_Wind_Sail_08Action.001'
  | '0_Wind_Sail_09Action.001'
  | '0_Wind_Sail_10Action.001'
  | '0_Wind_Sail_11Action.001'
  | '0_Wind_Sail_12Action.001'
  | '0_Wind_Sail_13Action.001'
  | '0_Wind_Sail_14Action.001'
  | '0_Wind_Sail_15Action.001'
  | '2_big_00Action.001'
  | '2_big_01Action.001'
  | '2_big_01aAction.001'
  | '2_big_02Action.001'
  | '2_big_03Action.001'
  | '2_big_04Action.001'
  | '2_big_05Action.001'
  | '2_big_06Action.001'
  | '2_big_07Action.001'
  | '2_big_08Action.001'
  | '2_big_09Action.001'
  | '2_big_09aAction.001'
  | '2_big_09BAction.001'
  | '2_big_10Action.001'
  | '2_big_11Action.001'
  | '2_big_11aAction.001'
  | '2_big_11bAction.001'
  | '2_boat_02Action.001'
  | '2_boat_03Action.001'
  | '2_boat_04Action.001'
  | '2_boat_05Action.001'
  | '2_boat_07Action.001'
  | '2_boat_08Action.001'
  | '2_boat_09Action.001'
  | '2_boat_10Action.001'
  | '2_boat_11Action.001'
  | '2_boat_12Action.001'
  | '2_boat_13Action.001'
  | '2_boat_14Action.001'
  | '2_boat_15Action.001'
  | '2_boat_16Action.001'
  | '2_boat_17Action.001'
  | '2_boat_18Action.001'
  | '2_boat_19Action.001'
  | '2_boat_20Action.001'
  | '2_cannon_00Action.001'
  | '2_cannon_01Action.001'
  | '2_cannon_02Action.001'
  | '2_cannon_03Action.001'
  | '2_cannon_04_Detached01Action.001'
  | '2_cannon_04_Detached02Action.001'
  | '2_cannon_04_Detached03Action.001'
  | '2_cannon_04_Detached04Action.001'
  | '2_cannon_04_Detached05Action.001'
  | '2_cannon_04_Detached06Action.001'
  | '2_cannon_04_Detached07Action.001'
  | '2_cannon_04_Detached08Action.001'
  | '2_cannon_04_Detached09Action.001'
  | '2_cannon_04_Detached10Action.001'
  | '2_cannon_04_Detached11Action.001'
  | '2_cannon_04_Detached12Action.001'
  | '2_cannon_04_Detached13Action.001'
  | '2_cannon_04_Detached14Action.001'
  | '2_cannon_04_Detached15Action.001'
  | '2_cannon_04_Detached16Action.001'
  | '2_cannon_04_Detached17Action.001'
  | '2_cannon_04_Detached18Action.001'
  | '2_cannon_04_Detached19Action.001'
  | '2_cannon_04_Detached20Action.001'
  | '2_cannon_04_Detached21Action.001'
  | '2_cannon_04_Detached22Action.001'
  | '2_cannon_04_Detached23Action.001'
  | '2_cannon_04_Detached24Action.001'
  | '2_cannon_04_Detached25Action.001'
  | '2_cannon_04_Detached26Action.001'
  | '2_cannon_04_Detached27Action.001'
  | '2_cannon_04_Detached28Action.001'
  | '2_cannon_04_Detached29Action.001'
  | '2_cannon_04_Detached30Action.001'
  | '2_cannon_04_Detached31Action.001'
  | '2_cannon_04_Detached32Action.001'
  | '2_cannon_05Action.001'
  | '2_cannon_smo_00Action.001'
  | '2_cannon_smo_01Action.001'
  | '2_cannon_smo_02Action.001'
  | '2_cannon_smo_03Action.001'
  | '2_cannon_smo_04Action.001'
  | '2_cannon_smo_05Action.001'
  | '2_center_00Action.001'
  | '2_center_01Action.001'
  | '2_center_03Action.001'
  | '2_center_04Action.001'
  | '2_center_05Action.001'
  | '2_center_08Action.001'
  | '2_center_09Action.001'
  | '2_center_10Action.001'
  | '2_center_11Action.001'
  | '2_center_12Action.001'
  | '2_center_13Action.001'
  | '2_center_14Action.001'
  | '2_center_15Action.001'
  | '2_center_16Action.001'
  | '2_center_17Action.001'
  | '2_center_18Action.001'
  | '2_center_19Action.001'
  | '2_center_20Action.001'
  | '2_center_21Action.001'
  | '2_center_22Action.001'
  | '2_center_23Action.001'
  | '2_center_24Action.001'
  | '2_center_25Action.001'
  | '2_center_26Action.001'
  | '2_center_27Action.001'
  | '2_center_28Action.001'
  | '2_figurehead_00Action.001'
  | '2_figurehead_01Action.001'
  | '2_figurehead_02Action.001'
  | '2_figurehead_03Action.001'
  | '2_figurehead_04Action.001'
  | '2_figurehead_05Action.001'
  | '2_figurehead_06Action.001'
  | '2_front_00Action.001'
  | '2_front_01Action.001'
  | '2_front_02Action.001'
  | '2_front_04Action.001'
  | '2_front_05Action.001'
  | '2_front_06Action.001'
  | '2_inside_00Action.001'
  | '2_inside_01Action.001'
  | '2_inside_02Action.001'
  | '2_inside_03Action.001'
  | '2_mast_01Action.001'
  | '2_mast_02Action.001'
  | '2_mast_03Action.001'
  | '2_mast_04Action.001'
  | '2_mast_05Action.001'
  | '2_mast_06Action.001'
  | '2_mast_07Action.001'
  | '2_mast_08Action.001'
  | '2_mast_09Action.001'
  | '2_mast_33Action.001'
  | '2_mast_35Action.001'
  | '2_mast_36Action.001'
  | '2_mast_38Action.001'
  | '2_mast_39Action.001'
  | '2_mast_40Action.001'
  | '2_mast_41Action.001'
  | '2_mast_43Action.001'
  | '2_mast_44Action.001'
  | '2_mast_46Action.001'
  | '2_mast_47Action.001'
  | '2_mast_48Action.001'
  | '2_mast_49Action.001'
  | '2_name_01Action.001'
  | '2_name_02Action.001'
  | '2_Rig_Smo_00Action.001'
  | '2_Rig_Smo_01Action.001'
  | '2_Rig_Smo_02Action.001'
  | '2_Rig_Smo_03Action.001'
  | '2_Rig_Smo_04Action.001'
  | '2_Rig_Smo_05Action.001'
  | '2_Rig_Smo_06Action.001'
  | '2_Rig_Smo_07Action.001'
  | '2_Rig_Smo_08Action.001'
  | '2_Rig_Smo_09Action.001'
  | '2_Rig_Smo_10Action.001'
  | '2_Rig_Smo_11Action.001'
  | '2_Rig_Smo_12Action.001'
  | '2_Rig_Smo_13Action.001'
  | '2_Rig_Smo_14Action.001'
  | '2_Rig_Smo_15Action.001'
  | '2_Rig_Smo_16Action.001'
  | '2_Rig_Smo_16.001Action.001'
  | '2_Rig_Smo_16aAction.001'
  | '2_Rig_Smo_17Action.001'
  | '2_Rig_Smo_18Action.001'
  | '2_Rig_Smo_19Action.001'
  | '2_Rig_Smo_20Action.001'
  | '2_Rig_Smo_21Action.001'
  | '2_Rig_Smo_22Action.001'
  | '2_Rig_Smo_23Action.001'
  | '2_ship_smooth_big_00Action.001'
  | '2_ship_smooth_big_01Action.001'
  | '2_ship_smooth_big_02Action.001'
  | '2_ship_smooth_big_03Action.001'
  | '2_ship_smooth_big_04Action.001'
  | '2_ship_smooth_big_05Action.001'
  | '2_sides_01Action.001'
  | '2_sides_02Action.001'
  | '2_sides_03Action.001'
  | '2_sides_04Action.001'
  | '2_sides_05Action.001'
  | '2_sides_06Action.001'
  | '2_sides_07Action.001'
  | '2_sides_08Action.001'
  | '2_sides_09Action.001'
  | '2_sides_10Action.001'
  | '2_sides_11Action.001'
  | '2_sides_12Action.001'
  | '2_sides_13Action.001'
  | '2_sides_14Action.001'
  | '2_sides_15Action.001'
  | '2_Stern_00Action.001'
  | '2_Stern_01Action.001'
  | '2_Stern_02Action.001'
  | '2_Stern_03Action.001'
  | '2_Stern_04Action.001'
  | '2_Stern_05Action.001'
  | '2_Stern_06Action.001'
  | '2_Stern_07Action.001'
  | '2_Stern_08Action.001'
  | '2_Stern_09Action.001'
  | '2_Stern_10Action.001'
  | '2_Stern_11Action.001'
  | 'NoWind_Sail_Rig_00'
  | 'NoWind_Sail_Rig_11'
  | 'NoWind_Sail_Rig_12'
  | 'NoWind_Sail_Rig_13'
  | 'NoWind_Sail_Rig_14'
  | 'NoWind_Sail_Rig_15'
  | 'NoWind_Sail_Rig_16'
  | 'NoWind_Sail_Rig_20'
  | 'NoWind_Sail_Rig_21'
  | 'NoWind_Sail_Rig_22'
  | 'NoWind_Sail_Rig_23'
  | 'NoWind_Sail_Rig_24'
  | 'NoWind_Sail_Rig_25'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/ocean.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  console.log(actions)


    useEffect(() => {
        Object.keys(actions).map((key,index) => {
            actions[key].play()
        })
    },[])


  return (
    <group ref={group} {...props} dispose={null}>
        <ambientLight  intensity={17}/>
        <directionalLight intensity={1.7} decay={2} color="#fffcf4" position={[4.08, 5.9, 5.66]} rotation={[-0.52, 0.96, 1.11]} />

        <PerspectiveCamera makeDefault fov={90} position={[100, 55, 95]} />
        <OrbitControls enableZoom={false}  minPolarAngle={1.5} maxPolarAngle={0.68}/>

      <group name="Scene">
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[-0.2, 1.35, -1.04]} />
        <mesh name="volume_shrinkwrap" geometry={nodes.volume_shrinkwrap.geometry} material={nodes.volume_shrinkwrap.material} position={[-35, 0, 0]} />
        <mesh name="0_Wind_Sail_00" geometry={nodes['0_Wind_Sail_00'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_01" geometry={nodes['0_Wind_Sail_01'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_02" geometry={nodes['0_Wind_Sail_02'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_03" geometry={nodes['0_Wind_Sail_03'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_04" geometry={nodes['0_Wind_Sail_04'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_05" geometry={nodes['0_Wind_Sail_05'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_06" geometry={nodes['0_Wind_Sail_06'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_07" geometry={nodes['0_Wind_Sail_07'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_08" geometry={nodes['0_Wind_Sail_08'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_09" geometry={nodes['0_Wind_Sail_09'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_10" geometry={nodes['0_Wind_Sail_10'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_11" geometry={nodes['0_Wind_Sail_11'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_12" geometry={nodes['0_Wind_Sail_12'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_13" geometry={nodes['0_Wind_Sail_13'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_14" geometry={nodes['0_Wind_Sail_14'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="0_Wind_Sail_15" geometry={nodes['0_Wind_Sail_15'].geometry} material={materials.Sail_Cloth} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_00" geometry={nodes['2_big_00'].geometry} material={materials.yellow_wood__with_normal} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_01" geometry={nodes['2_big_01'].geometry} material={materials.black_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_01a" geometry={nodes['2_big_01a'].geometry} material={materials.yellow_wood__with_normal} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_02" geometry={nodes['2_big_02'].geometry} material={materials.black_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_03" geometry={nodes['2_big_03'].geometry} material={materials.black_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_04" geometry={nodes['2_big_04'].geometry} material={materials.wood_floor} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_05" geometry={nodes['2_big_05'].geometry} material={materials.wood_floor} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_06" geometry={nodes['2_big_06'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_07" geometry={nodes['2_big_07'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_08" geometry={nodes['2_big_08'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_09" geometry={nodes['2_big_09'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_09a" geometry={nodes['2_big_09a'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_09B" geometry={nodes['2_big_09B'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_10" geometry={nodes['2_big_10'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_11" geometry={nodes['2_big_11'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_11a" geometry={nodes['2_big_11a'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_big_11b" geometry={nodes['2_big_11b'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_02" geometry={nodes['2_boat_02'].geometry} material={materials.white_board_bare} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_03" geometry={nodes['2_boat_03'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_04" geometry={nodes['2_boat_04'].geometry} material={materials.white_board} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_05" geometry={nodes['2_boat_05'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_07" geometry={nodes['2_boat_07'].geometry} material={materials.green_board} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_08" geometry={nodes['2_boat_08'].geometry} material={materials.white_board_bare} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_09" geometry={nodes['2_boat_09'].geometry} material={materials.white_board} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_10" geometry={nodes['2_boat_10'].geometry} material={materials.green_board} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_11" geometry={nodes['2_boat_11'].geometry} material={materials.white_board_bare} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_12" geometry={nodes['2_boat_12'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_13" geometry={nodes['2_boat_13'].geometry} material={materials.white_board} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_14" geometry={nodes['2_boat_14'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_15" geometry={nodes['2_boat_15'].geometry} material={materials.green_board} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_16" geometry={nodes['2_boat_16'].geometry} material={materials.white_board_bare} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_17" geometry={nodes['2_boat_17'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_18" geometry={nodes['2_boat_18'].geometry} material={materials.white_board} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_19" geometry={nodes['2_boat_19'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_boat_20" geometry={nodes['2_boat_20'].geometry} material={materials.black_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_00" geometry={nodes['2_cannon_00'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_01" geometry={nodes['2_cannon_01'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_02" geometry={nodes['2_cannon_02'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_03" geometry={nodes['2_cannon_03'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached01" geometry={nodes['2_cannon_04_Detached01'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached02" geometry={nodes['2_cannon_04_Detached02'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached03" geometry={nodes['2_cannon_04_Detached03'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached04" geometry={nodes['2_cannon_04_Detached04'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached05" geometry={nodes['2_cannon_04_Detached05'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached06" geometry={nodes['2_cannon_04_Detached06'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached07" geometry={nodes['2_cannon_04_Detached07'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached08" geometry={nodes['2_cannon_04_Detached08'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached09" geometry={nodes['2_cannon_04_Detached09'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached10" geometry={nodes['2_cannon_04_Detached10'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached11" geometry={nodes['2_cannon_04_Detached11'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached12" geometry={nodes['2_cannon_04_Detached12'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached13" geometry={nodes['2_cannon_04_Detached13'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached14" geometry={nodes['2_cannon_04_Detached14'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached15" geometry={nodes['2_cannon_04_Detached15'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached16" geometry={nodes['2_cannon_04_Detached16'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached17" geometry={nodes['2_cannon_04_Detached17'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached18" geometry={nodes['2_cannon_04_Detached18'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached19" geometry={nodes['2_cannon_04_Detached19'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached20" geometry={nodes['2_cannon_04_Detached20'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached21" geometry={nodes['2_cannon_04_Detached21'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached22" geometry={nodes['2_cannon_04_Detached22'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached23" geometry={nodes['2_cannon_04_Detached23'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached24" geometry={nodes['2_cannon_04_Detached24'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached25" geometry={nodes['2_cannon_04_Detached25'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached26" geometry={nodes['2_cannon_04_Detached26'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached27" geometry={nodes['2_cannon_04_Detached27'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached28" geometry={nodes['2_cannon_04_Detached28'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached29" geometry={nodes['2_cannon_04_Detached29'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached30" geometry={nodes['2_cannon_04_Detached30'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached31" geometry={nodes['2_cannon_04_Detached31'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_04_Detached32" geometry={nodes['2_cannon_04_Detached32'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_05" geometry={nodes['2_cannon_05'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_smo_00" geometry={nodes['2_cannon_smo_00'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_smo_01" geometry={nodes['2_cannon_smo_01'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_smo_02" geometry={nodes['2_cannon_smo_02'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_smo_03" geometry={nodes['2_cannon_smo_03'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_smo_04" geometry={nodes['2_cannon_smo_04'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_cannon_smo_05" geometry={nodes['2_cannon_smo_05'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_00" geometry={nodes['2_center_00'].geometry} material={materials.wood_dark_red_shiny} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_01" geometry={nodes['2_center_01'].geometry} material={materials.mesh} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_03" geometry={nodes['2_center_03'].geometry} material={materials.black_fabric} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_04" geometry={nodes['2_center_04'].geometry} material={materials.keg} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_05" geometry={nodes['2_center_05'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_08" geometry={nodes['2_center_08'].geometry} material={materials.red_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_09" geometry={nodes['2_center_09'].geometry} material={materials.Glass} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_10" geometry={nodes['2_center_10'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_11" geometry={nodes['2_center_11'].geometry} material={materials.wood_dark_brown} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_12" geometry={nodes['2_center_12'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_13" geometry={nodes['2_center_13'].geometry} material={materials.red_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_14" geometry={nodes['2_center_14'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_15" geometry={nodes['2_center_15'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_16" geometry={nodes['2_center_16'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_17" geometry={nodes['2_center_17'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_18" geometry={nodes['2_center_18'].geometry} material={materials.wood_dark_brown} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_19" geometry={nodes['2_center_19'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_20" geometry={nodes['2_center_20'].geometry} material={materials.red_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_21" geometry={nodes['2_center_21'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_22" geometry={nodes['2_center_22'].geometry} material={materials.red_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_23" geometry={nodes['2_center_23'].geometry} material={materials.Glass} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_24" geometry={nodes['2_center_24'].geometry} material={materials.red_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_25" geometry={nodes['2_center_25'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_26" geometry={nodes['2_center_26'].geometry} material={materials.wood_mahogney} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_27" geometry={nodes['2_center_27'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_center_28" geometry={nodes['2_center_28'].geometry} material={materials.wood_dark_brown} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_figurehead_00" geometry={nodes['2_figurehead_00'].geometry} material={materials.white} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_figurehead_01" geometry={nodes['2_figurehead_01'].geometry} material={materials.fake_fab_red} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_figurehead_02" geometry={nodes['2_figurehead_02'].geometry} material={materials.blue_fab} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_figurehead_03" geometry={nodes['2_figurehead_03'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_figurehead_04" geometry={nodes['2_figurehead_04'].geometry} material={materials.shield} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_figurehead_05" geometry={nodes['2_figurehead_05'].geometry} material={materials.Gold_disturbed} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_figurehead_06" geometry={nodes['2_figurehead_06'].geometry} material={materials.Material__211} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_front_00" geometry={nodes['2_front_00'].geometry} material={materials.blue} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_front_01" geometry={nodes['2_front_01'].geometry} material={materials.wood_floor} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_front_02" geometry={nodes['2_front_02'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_front_04" geometry={nodes['2_front_04'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_front_05" geometry={nodes['2_front_05'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_front_06" geometry={nodes['2_front_06'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_inside_00" geometry={nodes['2_inside_00'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_inside_01" geometry={nodes['2_inside_01'].geometry} material={materials.pale_wood2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_inside_02" geometry={nodes['2_inside_02'].geometry} material={materials.wood_dark_brown} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_inside_03" geometry={nodes['2_inside_03'].geometry} material={materials.red_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_01" geometry={nodes['2_mast_01'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_02" geometry={nodes['2_mast_02'].geometry} material={materials.flag3} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_03" geometry={nodes['2_mast_03'].geometry} material={materials.flag1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_04" geometry={nodes['2_mast_04'].geometry} material={materials.flag2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_36" geometry={nodes['2_mast_36'].geometry} material={materials.flag2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_44" geometry={nodes['2_mast_44'].geometry} material={materials.flag2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_05" geometry={nodes['2_mast_05'].geometry} material={materials.black_fabric} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_06" geometry={nodes['2_mast_06'].geometry} material={materials.mesh} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_35" geometry={nodes['2_mast_35'].geometry} material={materials.mesh} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_43" geometry={nodes['2_mast_43'].geometry} material={materials.mesh} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_07" geometry={nodes['2_mast_07'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_08" geometry={nodes['2_mast_08'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_09" geometry={nodes['2_mast_09'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_33" geometry={nodes['2_mast_33'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_38" geometry={nodes['2_mast_38'].geometry} material={materials.flag3} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_46" geometry={nodes['2_mast_46'].geometry} material={materials.flag3} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_39" geometry={nodes['2_mast_39'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_40" geometry={nodes['2_mast_40'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_41" geometry={nodes['2_mast_41'].geometry} material={materials.black_fabric} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_47" geometry={nodes['2_mast_47'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_48" geometry={nodes['2_mast_48'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_mast_49" geometry={nodes['2_mast_49'].geometry} material={materials.black_fabric} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_name_01" geometry={nodes['2_name_01'].geometry} material={materials.NAME1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_name_02" geometry={nodes['2_name_02'].geometry} material={materials.NAME2} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_00" geometry={nodes['2_Rig_Smo_00'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_15" geometry={nodes['2_Rig_Smo_15'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_23" geometry={nodes['2_Rig_Smo_23'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_01" geometry={nodes['2_Rig_Smo_01'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_22" geometry={nodes['2_Rig_Smo_22'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_02" geometry={nodes['2_Rig_Smo_02'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_03" geometry={nodes['2_Rig_Smo_03'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_04" geometry={nodes['2_Rig_Smo_04'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_05" geometry={nodes['2_Rig_Smo_05'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_06" geometry={nodes['2_Rig_Smo_06'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_09" geometry={nodes['2_Rig_Smo_09'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_17" geometry={nodes['2_Rig_Smo_17'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_07" geometry={nodes['2_Rig_Smo_07'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_08" geometry={nodes['2_Rig_Smo_08'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_10" geometry={nodes['2_Rig_Smo_10'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_11" geometry={nodes['2_Rig_Smo_11'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_12" geometry={nodes['2_Rig_Smo_12'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_13" geometry={nodes['2_Rig_Smo_13'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_14" geometry={nodes['2_Rig_Smo_14'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_16" geometry={nodes['2_Rig_Smo_16'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_16001" geometry={nodes['2_Rig_Smo_16001'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_16a" geometry={nodes['2_Rig_Smo_16a'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_18" geometry={nodes['2_Rig_Smo_18'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_19" geometry={nodes['2_Rig_Smo_19'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_20" geometry={nodes['2_Rig_Smo_20'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Rig_Smo_21" geometry={nodes['2_Rig_Smo_21'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_ship_smooth_big_00" geometry={nodes['2_ship_smooth_big_00'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_ship_smooth_big_01" geometry={nodes['2_ship_smooth_big_01'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_ship_smooth_big_02" geometry={nodes['2_ship_smooth_big_02'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_ship_smooth_big_03" geometry={nodes['2_ship_smooth_big_03'].geometry} material={materials.rope} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_ship_smooth_big_04" geometry={nodes['2_ship_smooth_big_04'].geometry} material={materials.rope_darker} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_ship_smooth_big_05" geometry={nodes['2_ship_smooth_big_05'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_01" geometry={nodes['2_sides_01'].geometry} material={materials.door} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_02" geometry={nodes['2_sides_02'].geometry} material={materials.red_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_03" geometry={nodes['2_sides_03'].geometry} material={materials.gate} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_04" geometry={nodes['2_sides_04'].geometry} material={materials.red_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_05" geometry={nodes['2_sides_05'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_06" geometry={nodes['2_sides_06'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_07" geometry={nodes['2_sides_07'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_08" geometry={nodes['2_sides_08'].geometry} material={materials.gate} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_09" geometry={nodes['2_sides_09'].geometry} material={materials.mesh} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_10" geometry={nodes['2_sides_10'].geometry} material={materials.red_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_11" geometry={nodes['2_sides_11'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_12" geometry={nodes['2_sides_12'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_13" geometry={nodes['2_sides_13'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_14" geometry={nodes['2_sides_14'].geometry} material={materials.gate} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_sides_15" geometry={nodes['2_sides_15'].geometry} material={materials.mesh} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_00" geometry={nodes['2_Stern_00'].geometry} material={materials.red_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_01" geometry={nodes['2_Stern_01'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_02" geometry={nodes['2_Stern_02'].geometry} material={materials.stern_deco_a} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_03" geometry={nodes['2_Stern_03'].geometry} material={materials.LOD_Lamp} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_04" geometry={nodes['2_Stern_04'].geometry} material={materials.black_wood} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_05" geometry={nodes['2_Stern_05'].geometry} material={materials.LOD_Win_Deco} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_06" geometry={nodes['2_Stern_06'].geometry} material={materials.yellow_wood_clean} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_07" geometry={nodes['2_Stern_07'].geometry} material={materials.LOD_Win} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_08" geometry={nodes['2_Stern_08'].geometry} material={materials.deco1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_09" geometry={nodes['2_Stern_09'].geometry} material={materials.LOD_back__deco} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_10" geometry={nodes['2_Stern_10'].geometry} material={materials.black_paint1} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
        <mesh name="2_Stern_11" geometry={nodes['2_Stern_11'].geometry} material={materials.LOD_side_deco_trans} position={[-0.14, -0.05, -1.32]} rotation={[1.49, -0.03, 0]} scale={0.01} />
         <mesh name="Plane"  geometry={nodes.Plane.geometry} material={materials.ocean} morphTargetDictionary={nodes.Plane.morphTargetDictionary} morphTargetInfluences={nodes.Plane.morphTargetInfluences} scale={2.06} />
      </group>
    </group>
  )
}

useGLTF.preload('/ocean.glb')
