/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    earth_color_10K: THREE.Mesh
    earth_color_10K001: THREE.Mesh
  }
  materials: {
    earth_color_10K: THREE.MeshStandardMaterial
    clouds: THREE.MeshStandardMaterial
  }
}

export function Model( {earthScale, cloudScale, ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/earthfinal.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
        <ambientLight/>
      <directionalLight intensity={1} decay={2} color="#fffcf4" position={[4.08, 5.9, 5.66]} rotation={[-0.52, 0.96, 1.11]} />

      <mesh geometry={nodes.earth_color_10K.geometry} material={materials.earth_color_10K} position={[0.21, 0.37, -0.07]} rotation={[0.55, 1.03, -0.61]} scale={earthScale} />
      <mesh geometry={nodes.earth_color_10K001.geometry} material={materials.clouds} position={[0.16, 0.39, -0.1]} rotation={[0.55, 1.03, -0.61]} scale={cloudScale} />
      <OrbitControls
       enableZoom={false}
       />
    </group>
  )
}

useGLTF.preload('/earthfinal.glb')
