/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    earth_color_10K: THREE.Mesh
    earth_color_10K001: THREE.Mesh
  }
  materials: {
    earth_color_10K: THREE.MeshStandardMaterial
    clouds: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/earth_new.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.earth_color_10K.geometry} material={materials.earth_color_10K} position={[2.99, -0.5, 1.34]} rotation={[0.55, 1.03, -0.61]} />
      <mesh geometry={nodes.earth_color_10K001.geometry} material={materials.clouds} position={[2.99, -0.5, 1.34]} rotation={[0.55, 1.03, -0.61]} />
    </group>
  )
}

useGLTF.preload('/earth_new.glb')
