/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    earth_color_10K: THREE.Mesh
    earth_color_10K001: THREE.Mesh
  }
  materials: {
    earth_color_10K: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/earth-transformed.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <directionalLight intensity={1366} decay={2} color="#fffcf4" position={[4.08, 5.9, 5.66]} rotation={[-0.52, 0.96, 1.11]} />
      <mesh geometry={nodes.earth_color_10K.geometry} material={materials.earth_color_10K} position={[0.7, 1.69, 0.68]} rotation={[0.59, 0.72, -1.15]} scale={6.88} />
      <mesh geometry={nodes.earth_color_10K001.geometry} material={materials.earth_color_10K} position={[0.7, 1.69, 0.68]} rotation={[0.59, 0.72, -1.15]} scale={7.01} />
    </group>
  )
}

useGLTF.preload('/earth-transformed.glb')
