/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gibraltar.glb --transform 
Files: gibraltar.glb [69.65MB] > /Users/vpdk/Desktop/HMSVICTORY/HMSVictoryRework/BAP/public/gibraltar-transformed.glb [5.01MB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gibraltar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BuildingMesh-00000002'].geometry} material={materials['BuildingMat-00000.001']} position={[-7.397, 0.812, 0.707]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00001002'].geometry} material={materials['BuildingMat-00001.003']} position={[-7.397, 0.812, 0.137]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00003002'].geometry} material={materials['BuildingMat-00003.003']} position={[-6.69, 0.812, 1.277]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00005001'].geometry} material={materials['BuildingMat-00005.004']} position={[-7.397, 0.812, -0.432]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00007001'].geometry} material={materials['BuildingMat-00007.004']} position={[-6.69, 0.812, 0.707]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00009001'].geometry} material={materials['BuildingMat-00009.006']} position={[-6.69, 0.812, 0.137]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00010001'].geometry} material={materials['BuildingMat-00010.005']} position={[-5.984, 0.14, 1.846]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00014001'].geometry} material={materials['BuildingMat-00014.004']} position={[-5.269, 0.786, 1.354]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00015001'].geometry} material={materials['BuildingMat-00015.006']} position={[-6.69, 1.484, -0.432]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00016001'].geometry} material={materials['BuildingMat-00016.006']} position={[-5.984, 0.812, 1.277]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00020001'].geometry} material={materials['BuildingMat-00020.006']} position={[-5.269, 0.786, 0.214]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00023001'].geometry} material={materials['BuildingMat-00023.004']} position={[-3.856, -0.558, 2.493]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00026001'].geometry} material={materials['BuildingMat-00026.004']} position={[-3.856, 0.786, 1.354]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00032001'].geometry} material={materials['BuildingMat-00032.005']} position={[-3.856, 0.786, 0.214]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00035001'].geometry} material={materials['BuildingMat-00035.004']} position={[-2.443, -0.559, 2.493]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00045001'].geometry} material={materials['BuildingMat-00045.004']} position={[-2.443, 0.786, 0.214]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00049001'].geometry} material={materials['BuildingMat-00049.006']} position={[-1.03, -0.559, 2.493]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00057001'].geometry} material={materials['BuildingMat-00057.004']} position={[-2.426, -1.955, -4.189]} rotation={[0, 0, 1.571]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00059001'].geometry} material={materials['BuildingMat-00059.006']} position={[0.4, 0.733, 0.369]} rotation={[0, 0, 1.571]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00061001'].geometry} material={materials['BuildingMat-00061.004']} position={[-1.03, 0.785, 0.214]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00067001'].geometry} material={materials['BuildingMat-00067.004']} position={[0.382, -0.56, 2.493]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00074001'].geometry} material={materials['BuildingMat-00074.006']} position={[1.795, -0.56, 4.772]} rotation={[0, 0, 1.57]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00079001'].geometry} material={materials['BuildingMat-00079.006']} position={[3.225, -1.956, 2.648]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00084001'].geometry} material={materials['BuildingMat-00084.004']} position={[3.226, 0.732, 0.368]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00091001'].geometry} material={materials['BuildingMat-00091.004']} position={[6.05, -1.958, 2.648]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00096001'].geometry} material={materials['BuildingMat-00096.003']} position={[6.052, 0.731, 0.368]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00099001'].geometry} material={materials['BuildingMat-00099.003']} position={[8.876, -1.96, 4.927]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00101'].geometry} material={materials['BuildingMat-00101.002']} position={[6.05, -1.958, -1.911]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00131001'].geometry} material={materials['BuildingMat-00131.003']} position={[0.399, -1.956, -1.91]} rotation={[0, 0, 1.571]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00153001'].geometry} material={materials['BuildingMat-00153.003']} position={[3.225, -1.957, -1.911]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00103'].geometry} material={materials['BuildingMat-00103.005']} position={[8.876, -1.959, 2.648]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00106'].geometry} material={materials['BuildingMat-00106.006']} position={[6.05, -1.958, -4.19]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00108'].geometry} material={materials['BuildingMat-00108.006']} position={[8.876, -1.959, 0.368]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00114'].geometry} material={materials['BuildingMat-00114.003']} position={[8.875, -1.959, -1.911]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00002003'].geometry} material={materials['BuildingMat-00002.002']} position={[-8.103, -0.532, 3.555]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00005002'].geometry} material={materials['BuildingMat-00005.005']} position={[-8.103, -0.532, 2.986]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00007002'].geometry} material={materials['BuildingMat-00007.005']} position={[-8.103, 0.14, 1.846]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00009002'].geometry} material={materials['BuildingMat-00009.007']} position={[-8.103, -0.532, 2.416]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00011002'].geometry} material={materials['BuildingMat-00011.005']} position={[-8.103, 0.14, 1.277]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00015002'].geometry} material={materials['BuildingMat-00015.007']} position={[-8.809, 0.14, 1.277]} rotation={[0, 0, Math.PI / 2]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00017002'].geometry} material={materials['BuildingMat-00017.005']} position={[-8.103, 0.14, 0.707]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00019002'].geometry} material={materials['BuildingMat-00019.005']} position={[-8.809, 0.14, 1.846]} rotation={[0, 0, Math.PI / 2]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00020002'].geometry} material={materials['BuildingMat-00020.007']} position={[-7.397, -0.532, 4.125]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00022002'].geometry} material={materials['BuildingMat-00022.003']} position={[-8.809, 0.14, 0.707]} rotation={[0, 0, Math.PI / 2]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00023002'].geometry} material={materials['BuildingMat-00023.005']} position={[-7.397, -0.532, 3.555]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00026002'].geometry} material={materials['BuildingMat-00026.005']} position={[-7.397, 0.14, 2.986]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00029002'].geometry} material={materials['BuildingMat-00029.005']} position={[-7.397, 0.14, 2.416]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00031002'].geometry} material={materials['BuildingMat-00031.005']} position={[-7.397, 0.14, 1.846]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00033002'].geometry} material={materials['BuildingMat-00033.003']} position={[-8.103, -0.532, 0.137]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00034002'].geometry} material={materials['BuildingMat-00034.001']} position={[-6.681, 0.786, 1.354]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00039002'].geometry} material={materials['BuildingMat-00039.005']} position={[-8.103, -0.532, -0.432]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00040002'].geometry} material={materials['BuildingMat-00040.003']} position={[-6.681, 0.786, 0.214]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00044002'].geometry} material={materials['BuildingMat-00044.003']} position={[-6.69, -0.532, 4.125]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00045002'].geometry} material={materials['BuildingMat-00045.005']} position={[-8.103, -0.532, -1.002]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00048002'].geometry} material={materials['BuildingMat-00048.005']} position={[-6.69, -0.532, 3.555]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00049002'].geometry} material={materials['BuildingMat-00049.007']} position={[-8.103, -0.532, -1.571]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00050002'].geometry} material={materials['BuildingMat-00050.003']} position={[-6.69, 0.14, 2.986]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00052002'].geometry} material={materials['BuildingMat-00052.005']} position={[-6.69, 0.14, 2.416]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00054002'].geometry} material={materials['BuildingMat-00054.003']} position={[-6.69, 0.14, 1.846]} rotation={[0, 0, 1.571]} scale={0.003} />
      <mesh geometry={nodes['BuildingMesh-00055002'].geometry} material={materials['BuildingMat-00055.005']} position={[-6.682, -0.558, -0.925]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00056002'].geometry} material={materials['BuildingMat-00056.003']} position={[-5.269, -0.558, 4.772]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00059002'].geometry} material={materials['BuildingMat-00059.007']} position={[-5.269, -0.558, 3.632]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00060002'].geometry} material={materials['BuildingMat-00060.003']} position={[-5.269, -0.558, 2.493]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00063002'].geometry} material={materials['BuildingMat-00063.005']} position={[-6.682, -0.558, -2.064]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00066002'].geometry} material={materials['BuildingMat-00066.005']} position={[-6.682, -0.558, -3.203]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00068002'].geometry} material={materials['BuildingMat-00068.003']} position={[-3.856, -0.559, 5.911]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00069002'].geometry} material={materials['BuildingMat-00069.003']} position={[-6.682, -0.559, -4.343]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00070002'].geometry} material={materials['BuildingMat-00070.003']} position={[-5.269, -0.558, -0.925]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00071002'].geometry} material={materials['BuildingMat-00071.003']} position={[-3.856, -0.559, 4.772]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00073002'].geometry} material={materials['BuildingMat-00073.004']} position={[-3.856, -0.558, 3.632]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00077002'].geometry} material={materials['BuildingMat-00077.005']} position={[-5.269, -0.558, -2.064]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00082002'].geometry} material={materials['BuildingMat-00082.001']} position={[-5.269, -0.559, -3.204]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00085002'].geometry} material={materials['BuildingMat-00085.003']} position={[-2.443, -0.559, 5.911]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00086002'].geometry} material={materials['BuildingMat-00086.003']} position={[-5.269, -0.559, -4.343]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00087002'].geometry} material={materials['BuildingMat-00087.003']} position={[-2.443, -0.559, 4.772]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00088002'].geometry} material={materials['BuildingMat-00088.003']} position={[-3.856, -0.559, -0.925]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00089002'].geometry} material={materials['BuildingMat-00089.003']} position={[-5.269, -0.559, -5.482]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00090002'].geometry} material={materials['BuildingMat-00090.001']} position={[-2.443, -0.559, 3.633]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00093002'].geometry} material={materials['BuildingMat-00093.003']} position={[-2.443, 0.786, 1.354]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00095002'].geometry} material={materials['BuildingMat-00095.003']} position={[-3.856, -0.559, -2.064]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00098002'].geometry} material={materials['BuildingMat-00098.003']} position={[-3.856, -0.559, -3.204]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00101001'].geometry} material={materials['BuildingMat-00101.003']} position={[-1.031, -0.559, 5.912]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00102001'].geometry} material={materials['BuildingMat-00102.002']} position={[-3.856, -0.559, -4.343]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00104001'].geometry} material={materials['BuildingMat-00104.004']} position={[-2.443, -0.559, -0.925]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00105001'].geometry} material={materials['BuildingMat-00105.005']} position={[-1.03, -0.559, 4.772]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00106001'].geometry} material={materials['BuildingMat-00106.007']} position={[-3.857, -0.559, -5.482]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00107001'].geometry} material={materials['BuildingMat-00107.004']} position={[-1.03, -0.559, 3.633]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00109001'].geometry} material={materials['BuildingMat-00109.005']} position={[-1.03, 0.785, 1.354]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00112001'].geometry} material={materials['BuildingMat-00112.003']} position={[-2.443, -0.559, -2.064]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00115001'].geometry} material={materials['BuildingMat-00115.003']} position={[-2.443, -0.559, -3.204]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00119001'].geometry} material={materials['BuildingMat-00119.003']} position={[0.382, -0.56, 5.912]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00120001'].geometry} material={materials['BuildingMat-00120.002']} position={[-2.444, -0.559, -4.343]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00122001'].geometry} material={materials['BuildingMat-00122.002']} position={[0.382, -0.56, 4.772]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00123001'].geometry} material={materials['BuildingMat-00123.003']} position={[-1.03, -0.559, -0.925]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00124001'].geometry} material={materials['BuildingMat-00124.003']} position={[-2.444, -0.56, -5.483]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00126001'].geometry} material={materials['BuildingMat-00126.003']} position={[0.382, -0.56, 3.633]} rotation={[0, 0, 1.57]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00127001'].geometry} material={materials['BuildingMat-00127.003']} position={[0.383, 0.785, 1.354]} rotation={[0, 0, 1.57]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00132001'].geometry} material={materials['BuildingMat-00132.003']} position={[0.383, 0.785, 0.214]} rotation={[0, 0, 1.571]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00138001'].geometry} material={materials['BuildingMat-00138.003']} position={[0.399, -1.956, -4.189]} rotation={[0, 0, 1.571]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00140001'].geometry} material={materials['BuildingMat-00140.002']} position={[3.225, -1.957, 4.927]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00141001'].geometry} material={materials['BuildingMat-00141.003']} position={[0.382, -0.56, -0.925]} rotation={[0, 0, 1.57]} scale={0.006} />
      <mesh geometry={nodes['BuildingMesh-00156001'].geometry} material={materials['BuildingMat-00156.003']} position={[3.225, -1.957, -4.19]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['BuildingMesh-00157001'].geometry} material={materials['BuildingMat-00157.003']} position={[6.05, -1.958, 4.927]} rotation={[0, 0, 1.57]} scale={0.011} />
      <mesh geometry={nodes['0_Wind_Sail_00'].geometry} material={materials['Sail_Cloth.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_big_00'].geometry} material={materials['yellow_wood__with_normal.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_big_01'].geometry} material={materials['black_wood.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_big_05'].geometry} material={materials['wood_floor.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_big_06'].geometry} material={materials['yellow_wood_clean.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_big_07'].geometry} material={materials['black_paint1.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_boat_02'].geometry} material={materials['white_board_bare.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_boat_04'].geometry} material={materials['white_board.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_boat_07'].geometry} material={materials['green_board.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_cannon_02'].geometry} material={materials['pale_wood2.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_cannon_smo_00'].geometry} material={materials['rope.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_cannon_smo_03'].geometry} material={materials['rope_darker.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_center_00'].geometry} material={materials['wood_dark_red_shiny.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_center_01'].geometry} material={materials['mesh.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_center_03'].geometry} material={materials['black_fabric.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_center_04'].geometry} material={materials['keg.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_center_08'].geometry} material={materials['red_wood.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_center_09'].geometry} material={materials['Glass.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_center_11'].geometry} material={materials['wood_dark_brown.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_center_26'].geometry} material={materials['wood_mahogney.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_figurehead_05'].geometry} material={materials['Gold_disturbed.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_figurehead_06'].geometry} material={materials['Material__211.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_front_00'].geometry} material={materials['blue.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_mast_02'].geometry} material={materials['flag3.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_mast_03'].geometry} material={materials['flag1.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_mast_04'].geometry} material={materials['flag2.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_name_01'].geometry} material={materials['NAME1.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_sides_01'].geometry} material={materials['door.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_sides_03'].geometry} material={materials['gate.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_sides_04'].geometry} material={materials['red_wood_clean.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_Stern_02'].geometry} material={materials['stern_deco_a.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_Stern_03'].geometry} material={materials['LOD_Lamp.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_Stern_05'].geometry} material={materials['LOD_Win_Deco.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_Stern_07'].geometry} material={materials['LOD_Win.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_Stern_08'].geometry} material={materials['deco1.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_Stern_09'].geometry} material={materials['LOD_back__deco.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
      <mesh geometry={nodes['2_Stern_11'].geometry} material={materials['LOD_side_deco_trans.003']} position={[-0.427, -0.037, 0.129]} rotation={[Math.PI / 2, 0, -2.607]} scale={0.023} />
    </group>
  )
}

useGLTF.preload('/gibraltar-transformed.glb')
