/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { OrbitControls, PerspectiveCamera, useGLTF } from "@react-three/drei";
import dynamic from "next/dynamic";
const Ship = dynamic(() => import('@/components/canvas/ship').then((mod) => mod.Ship), { ssr: false })

export function Model(props) {
    const { nodes, materials } = useGLTF("/CapeStVincent.glb");
    const animationRef = useRef()

    return (
        <group {...props} dispose={null}>
            <ambientLight />
            <PerspectiveCamera makeDefault fov={5} position={[7, 3, 7]} zoom={1} />
            <OrbitControls enableZoom={false} minPolarAngle={0} maxPolarAngle={1.5} />
            <mesh ref={animationRef}><Ship scale={0.5} distances={[0, 20]} rotation={[0,180,0]} position={[-0.868, 0.2, 4.269]} /></mesh>

            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00008"].geometry}
                material={materials["BuildingMat-00008.002"]}
                position={[3.044, -0.345, 6.019]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00009"].geometry}
                material={materials["BuildingMat-00009.002"]}
                position={[3.044, -0.344, 5.246]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00010"].geometry}
                material={materials["BuildingMat-00010.002"]}
                position={[3.044, -0.344, 4.473]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00011"].geometry}
                material={materials["BuildingMat-00011.002"]}
                position={[3.044, -0.344, 3.7]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00012"].geometry}
                material={materials["BuildingMat-00012.002"]}
                position={[3.044, -0.344, 2.927]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00015"].geometry}
                material={materials["BuildingMat-00015.002"]}
                position={[3.044, -0.344, 2.154]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00016"].geometry}
                material={materials["BuildingMat-00016.002"]}
                position={[3.044, -0.344, 1.381]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00019"].geometry}
                material={materials["BuildingMat-00019.002"]}
                position={[3.044, -0.344, 0.608]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00020"].geometry}
                material={materials["BuildingMat-00020.002"]}
                position={[3.044, -0.344, -0.165]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00021"].geometry}
                material={materials["BuildingMat-00021.002"]}
                position={[3.044, -0.344, -0.938]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00027"].geometry}
                material={materials["BuildingMat-00027.002"]}
                position={[2.075, -0.345, 6.019]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00028"].geometry}
                material={materials["BuildingMat-00028.002"]}
                position={[2.076, -0.344, 0.608]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00029"].geometry}
                material={materials["BuildingMat-00029.002"]}
                position={[2.075, -0.345, 5.246]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00030"].geometry}
                material={materials["BuildingMat-00030.002"]}
                position={[2.076, -0.344, -0.165]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00031"].geometry}
                material={materials["BuildingMat-00031.002"]}
                position={[2.076, -0.344, 4.473]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00032"].geometry}
                material={materials["BuildingMat-00032.002"]}
                position={[2.076, -0.344, 3.7]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00036"].geometry}
                material={materials["BuildingMat-00036.002"]}
                position={[2.076, -0.344, 2.927]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00038"].geometry}
                material={materials["BuildingMat-00038.002"]}
                position={[2.076, -0.344, 2.154]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00039"].geometry}
                material={materials["BuildingMat-00039.002"]}
                position={[2.076, -0.344, 1.381]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00041"].geometry}
                material={materials["BuildingMat-00041.002"]}
                position={[2.076, -0.344, -0.938]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00042"].geometry}
                material={materials["BuildingMat-00042.002"]}
                position={[1.119, -0.38, 3.036]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00046"].geometry}
                material={materials["BuildingMat-00046.002"]}
                position={[2.076, 0.577, 0.608]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00048"].geometry}
                material={materials["BuildingMat-00048.002"]}
                position={[2.076, 0.577, -0.165]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00049"].geometry}
                material={materials["BuildingMat-00049.002"]}
                position={[1.119, -0.379, 1.49]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00052"].geometry}
                material={materials["BuildingMat-00052.002"]}
                position={[1.119, -0.379, -0.056]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00053"].geometry}
                material={materials["BuildingMat-00053.002"]}
                position={[1.119, -0.38, 6.128]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00055"].geometry}
                material={materials["BuildingMat-00055.002"]}
                position={[1.119, -0.38, 4.582]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00059"].geometry}
                material={materials["BuildingMat-00059.002"]}
                position={[-0.817, -0.38, 3.036]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00061"].geometry}
                material={materials["BuildingMat-00061.002"]}
                position={[-0.817, -0.38, 1.49]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00063"].geometry}
                material={materials["BuildingMat-00063.002"]}
                position={[-0.817, -0.379, -0.056]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00064"].geometry}
                material={materials["BuildingMat-00064.002"]}
                position={[-0.818, -0.38, 6.128]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00066"].geometry}
                material={materials["BuildingMat-00066.002"]}
                position={[-0.817, -0.38, 4.582]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00073"].geometry}
                material={materials["BuildingMat-00073.002"]}
                position={[-2.754, -0.38, 1.49]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00074"].geometry}
                material={materials["BuildingMat-00074.002"]}
                position={[-2.754, -0.38, -0.056]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00075"].geometry}
                material={materials["BuildingMat-00075.002"]}
                position={[-2.754, -0.38, 6.128]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00077"].geometry}
                material={materials["BuildingMat-00077.002"]}
                position={[-2.754, -0.38, 4.582]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00079"].geometry}
                material={materials["BuildingMat-00079.002"]}
                position={[-2.754, -0.38, 3.036]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00103001"].geometry}
                material={materials["BuildingMat-00103.001"]}
                position={[1.107, -0.344, 2.927]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00104001"].geometry}
                material={materials["BuildingMat-00104.001"]}
                position={[1.107, -0.344, 2.154]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00105001"].geometry}
                material={materials["BuildingMat-00105.001"]}
                position={[0.139, 0.577, 2.927]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00106001"].geometry}
                material={materials["BuildingMat-00106.001"]}
                position={[0.139, 0.577, 2.154]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00107001"].geometry}
                material={materials["BuildingMat-00107.001"]}
                position={[0.139, -0.344, 2.927]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00108001"].geometry}
                material={materials["BuildingMat-00108.001"]}
                position={[1.107, 0.577, 2.154]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00109001"].geometry}
                material={materials["BuildingMat-00109.001"]}
                position={[0.139, -0.344, 2.154]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
        </group>
    );
}

useGLTF.preload("/CapeStVincent.glb");
