/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { OrbitControls, PerspectiveCamera, useFBX, useGLTF } from "@react-three/drei";
import dynamic from "next/dynamic";
import { useFrame } from "@react-three/fiber";

const Ship = dynamic(() => import('@/components/canvas/ship').then((mod) => mod.Ship), { ssr: false })

export function Model(props) {
    const { nodes, materials } = useGLTF("/gibraltarNew.glb");
    const animationRef = useRef()

    return (
        <group {...props} dispose={null}>
            <ambientLight />
            <PerspectiveCamera makeDefault fov={90} position={[7, 3, 7]} zoom={1} />
            <OrbitControls enableZoom={false} minPolarAngle={0} maxPolarAngle={1.5} />
            <mesh ref={animationRef}><Ship scale={0.2} distances={[0, 20]} position={[0, 0, -5.269]} /></mesh>

            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00000002"].geometry}
                material={materials["BuildingMat-00000.002"]}
                position={[-9.554, 1.164, 0.793]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00001002"].geometry}
                material={materials["BuildingMat-00001.002"]}
                position={[-9.554, 1.164, 0.012]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00003002"].geometry}
                material={materials["BuildingMat-00003.002"]}
                position={[-8.585, 1.164, 1.573]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00005001"].geometry}
                material={materials["BuildingMat-00005.001"]}
                position={[-9.554, 1.164, -0.769]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00006001"].geometry}
                material={materials["BuildingMat-00006.001"]}
                position={[-9.554, 0.242, -0.769]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00007001"].geometry}
                material={materials["BuildingMat-00007.001"]}
                position={[-8.585, 1.164, 0.793]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00008001"].geometry}
                material={materials["BuildingMat-00008.001"]}
                position={[-9.554, 2.085, 0.012]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00009001"].geometry}
                material={materials["BuildingMat-00009.001"]}
                position={[-8.585, 1.164, 0.012]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00010001"].geometry}
                material={materials["BuildingMat-00010.001"]}
                position={[-7.617, 0.242, 2.354]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00012001"].geometry}
                material={materials["BuildingMat-00012.001"]}
                position={[-8.585, 2.085, 0.012]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00013001"].geometry}
                material={materials["BuildingMat-00013.001"]}
                position={[-9.554, 2.085, -0.769]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00014001"].geometry}
                material={materials["BuildingMat-00014.001"]}
                position={[-6.636, 1.128, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00015001"].geometry}
                material={materials["BuildingMat-00015.001"]}
                position={[-8.585, 2.085, -0.769]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00016001"].geometry}
                material={materials["BuildingMat-00016.001"]}
                position={[-7.617, 1.164, 1.573]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00017001"].geometry}
                material={materials["BuildingMat-00017.001"]}
                position={[-8.585, 1.164, -0.769]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00023001"].geometry}
                material={materials["BuildingMat-00023.001"]}
                position={[-4.7, -0.715, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00026001"].geometry}
                material={materials["BuildingMat-00026.001"]}
                position={[-4.7, 1.128, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00032001"].geometry}
                material={materials["BuildingMat-00032.001"]}
                position={[-4.7, 1.128, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00035001"].geometry}
                material={materials["BuildingMat-00035.001"]}
                position={[-2.763, -0.715, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00045001"].geometry}
                material={materials["BuildingMat-00045.001"]}
                position={[-2.763, 1.128, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00049001"].geometry}
                material={materials["BuildingMat-00049.001"]}
                position={[-0.827, -0.716, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00057001"].geometry}
                material={materials["BuildingMat-00057.001"]}
                position={[-2.74, -2.63, -5.919]}
                rotation={[0, 0, 1.571]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00059001"].geometry}
                material={materials["BuildingMat-00059.001"]}
                position={[1.135, 1.056, 0.329]}
                rotation={[0, 0, 1.571]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00061001"].geometry}
                material={materials["BuildingMat-00061.001"]}
                position={[-0.826, 1.127, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00062001"].geometry}
                material={materials["BuildingMat-00062.001"]}
                position={[1.133, -2.63, 0.329]}
                rotation={[0, 0, 1.571]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00067001"].geometry}
                material={materials["BuildingMat-00067.001"]}
                position={[1.11, -0.716, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00074001"].geometry}
                material={materials["BuildingMat-00074.001"]}
                position={[3.047, -0.717, 6.365]}
                rotation={[0, 0, 1.57]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00079001"].geometry}
                material={materials["BuildingMat-00079.001"]}
                position={[5.007, -2.631, 3.453]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00084001"].geometry}
                material={materials["BuildingMat-00084.001"]}
                position={[5.008, 1.054, 0.328]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00091001"].geometry}
                material={materials["BuildingMat-00091.001"]}
                position={[8.88, -2.633, 3.453]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00096001"].geometry}
                material={materials["BuildingMat-00096.001"]}
                position={[8.882, 1.053, 0.328]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00099001"].geometry}
                material={materials["BuildingMat-00099.001"]}
                position={[12.753, -2.636, 6.578]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00101"].geometry}
                material={materials["BuildingMat-00101"]}
                position={[8.879, -2.633, -2.796]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00103"].geometry}
                material={materials["BuildingMat-00103"]}
                position={[12.753, -2.635, 3.453]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00106"].geometry}
                material={materials["BuildingMat-00106"]}
                position={[8.879, -2.634, -5.92]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00108"].geometry}
                material={materials["BuildingMat-00108"]}
                position={[12.753, -2.635, 0.328]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00114"].geometry}
                material={materials["BuildingMat-00114"]}
                position={[12.753, -2.635, -2.796]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00002003"].geometry}
                material={materials["BuildingMat-00002.003"]}
                position={[-10.522, -0.679, 4.697]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00005002"].geometry}
                material={materials["BuildingMat-00005.002"]}
                position={[-10.522, -0.679, 3.916]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00007002"].geometry}
                material={materials["BuildingMat-00007.002"]}
                position={[-10.522, 0.242, 2.354]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00011002"].geometry}
                material={materials["BuildingMat-00011.002"]}
                position={[-10.522, 0.242, 1.573]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00014002"].geometry}
                material={materials["BuildingMat-00014.002"]}
                position={[-10.522, -0.679, 2.354]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00015002"].geometry}
                material={materials["BuildingMat-00015.002"]}
                position={[-11.49, 0.242, 1.573]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00016002"].geometry}
                material={materials["BuildingMat-00016.002"]}
                position={[-10.522, 0.242, 3.135]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00017002"].geometry}
                material={materials["BuildingMat-00017.002"]}
                position={[-10.522, 0.242, 0.793]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00019002"].geometry}
                material={materials["BuildingMat-00019.002"]}
                position={[-11.49, 0.242, 2.354]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00020002"].geometry}
                material={materials["BuildingMat-00020.002"]}
                position={[-9.554, -0.679, 5.478]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00022002"].geometry}
                material={materials["BuildingMat-00022.002"]}
                position={[-11.49, 0.242, 0.793]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00023002"].geometry}
                material={materials["BuildingMat-00023.002"]}
                position={[-9.554, -0.679, 4.697]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00026002"].geometry}
                material={materials["BuildingMat-00026.002"]}
                position={[-9.554, 0.242, 3.916]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00027002"].geometry}
                material={materials["BuildingMat-00027.002"]}
                position={[-10.522, -0.679, 0.793]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00028002"].geometry}
                material={materials["BuildingMat-00028.002"]}
                position={[-9.554, -0.679, 3.916]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00029002"].geometry}
                material={materials["BuildingMat-00029.002"]}
                position={[-9.554, 0.242, 3.135]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00031002"].geometry}
                material={materials["BuildingMat-00031.002"]}
                position={[-9.554, 0.242, 2.354]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00033002"].geometry}
                material={materials["BuildingMat-00033.002"]}
                position={[-10.522, -0.679, 0.012]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00034002"].geometry}
                material={materials["BuildingMat-00034.002"]}
                position={[-8.573, 1.128, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00035002"].geometry}
                material={materials["BuildingMat-00035.002"]}
                position={[-10.522, 0.242, 0.012]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00036002"].geometry}
                material={materials["BuildingMat-00036.002"]}
                position={[-9.554, -0.679, 3.135]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00038002"].geometry}
                material={materials["BuildingMat-00038.002"]}
                position={[-8.573, -0.715, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00039002"].geometry}
                material={materials["BuildingMat-00039.002"]}
                position={[-10.522, -0.679, -0.769]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00042002"].geometry}
                material={materials["BuildingMat-00042.002"]}
                position={[-9.554, 0.242, 4.697]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00044002"].geometry}
                material={materials["BuildingMat-00044.002"]}
                position={[-8.585, -0.679, 5.478]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00045002"].geometry}
                material={materials["BuildingMat-00045.002"]}
                position={[-10.522, -0.679, -1.55]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00046002"].geometry}
                material={materials["BuildingMat-00046.002"]}
                position={[-8.573, -0.715, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00047002"].geometry}
                material={materials["BuildingMat-00047.002"]}
                position={[-10.522, 0.242, -0.769]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00048002"].geometry}
                material={materials["BuildingMat-00048.002"]}
                position={[-8.585, -0.679, 4.697]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00049002"].geometry}
                material={materials["BuildingMat-00049.002"]}
                position={[-10.522, -0.679, -2.331]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00050002"].geometry}
                material={materials["BuildingMat-00050.002"]}
                position={[-8.585, 0.242, 3.916]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00051002"].geometry}
                material={materials["BuildingMat-00051.002"]}
                position={[-8.585, 0.242, 4.697]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00052002"].geometry}
                material={materials["BuildingMat-00052.002"]}
                position={[-8.585, 0.242, 3.135]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00054002"].geometry}
                material={materials["BuildingMat-00054.002"]}
                position={[-8.585, 0.242, 2.354]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00055002"].geometry}
                material={materials["BuildingMat-00055.002"]}
                position={[-8.573, -0.715, -1.444]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00056002"].geometry}
                material={materials["BuildingMat-00056.002"]}
                position={[-6.637, -0.715, 6.365]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00057002"].geometry}
                material={materials["BuildingMat-00057.002"]}
                position={[-8.585, -0.679, 3.916]}
                rotation={[0, 0, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00059002"].geometry}
                material={materials["BuildingMat-00059.002"]}
                position={[-6.637, -0.715, 4.803]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00060002"].geometry}
                material={materials["BuildingMat-00060.002"]}
                position={[-6.637, -0.715, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00062002"].geometry}
                material={materials["BuildingMat-00062.002"]}
                position={[-6.636, 1.128, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00063002"].geometry}
                material={materials["BuildingMat-00063.002"]}
                position={[-8.574, -0.715, -3.006]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00064002"].geometry}
                material={materials["BuildingMat-00064.002"]}
                position={[-6.637, -0.715, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00066002"].geometry}
                material={materials["BuildingMat-00066.002"]}
                position={[-8.574, -0.715, -4.568]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00068002"].geometry}
                material={materials["BuildingMat-00068.002"]}
                position={[-4.7, -0.716, 7.927]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00069002"].geometry}
                material={materials["BuildingMat-00069.002"]}
                position={[-8.574, -0.715, -6.13]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00070002"].geometry}
                material={materials["BuildingMat-00070.002"]}
                position={[-6.637, -0.715, -1.444]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00071002"].geometry}
                material={materials["BuildingMat-00071.002"]}
                position={[-4.7, -0.715, 6.365]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00073002"].geometry}
                material={materials["BuildingMat-00073.002"]}
                position={[-4.7, -0.715, 4.803]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00074002"].geometry}
                material={materials["BuildingMat-00074.002"]}
                position={[-4.7, -0.715, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00076002"].geometry}
                material={materials["BuildingMat-00076.002"]}
                position={[-4.7, 1.128, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00077002"].geometry}
                material={materials["BuildingMat-00077.002"]}
                position={[-6.637, -0.715, -3.006]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00078002"].geometry}
                material={materials["BuildingMat-00078.002"]}
                position={[-4.7, 1.128, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00079002"].geometry}
                material={materials["BuildingMat-00079.002"]}
                position={[-4.7, -0.715, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00081002"].geometry}
                material={materials["BuildingMat-00081.002"]}
                position={[-4.7, 1.128, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00082002"].geometry}
                material={materials["BuildingMat-00082.002"]}
                position={[-6.637, -0.715, -4.568]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00084002"].geometry}
                material={materials["BuildingMat-00084.002"]}
                position={[-4.7, -0.715, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00085002"].geometry}
                material={materials["BuildingMat-00085.002"]}
                position={[-2.764, -0.716, 7.927]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00086002"].geometry}
                material={materials["BuildingMat-00086.002"]}
                position={[-6.637, -0.715, -6.13]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00087002"].geometry}
                material={materials["BuildingMat-00087.002"]}
                position={[-2.763, -0.716, 6.365]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00088002"].geometry}
                material={materials["BuildingMat-00088.002"]}
                position={[-4.7, -0.715, -1.445]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00089002"].geometry}
                material={materials["BuildingMat-00089.002"]}
                position={[-6.637, -0.716, -7.692]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00090002"].geometry}
                material={materials["BuildingMat-00090.002"]}
                position={[-2.764, -0.715, 4.803]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00091002"].geometry}
                material={materials["BuildingMat-00091.002"]}
                position={[-2.763, -0.715, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00092002"].geometry}
                material={materials["BuildingMat-00092.002"]}
                position={[-2.763, 1.128, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00093002"].geometry}
                material={materials["BuildingMat-00093.002"]}
                position={[-2.763, 1.128, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00095002"].geometry}
                material={materials["BuildingMat-00095.002"]}
                position={[-4.7, -0.715, -3.007]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00097002"].geometry}
                material={materials["BuildingMat-00097.002"]}
                position={[-2.763, 1.127, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00098002"].geometry}
                material={materials["BuildingMat-00098.002"]}
                position={[-4.7, -0.715, -4.568]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00100002"].geometry}
                material={materials["BuildingMat-00100.002"]}
                position={[-2.764, -0.715, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00101001"].geometry}
                material={materials["BuildingMat-00101.001"]}
                position={[-0.827, -0.716, 7.927]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00102001"].geometry}
                material={materials["BuildingMat-00102.001"]}
                position={[-4.701, -0.716, -6.13]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00104001"].geometry}
                material={materials["BuildingMat-00104.001"]}
                position={[-2.763, -0.715, -1.445]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00105001"].geometry}
                material={materials["BuildingMat-00105.001"]}
                position={[-0.827, -0.716, 6.365]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00106001"].geometry}
                material={materials["BuildingMat-00106.001"]}
                position={[-4.701, -0.716, -7.692]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00107001"].geometry}
                material={materials["BuildingMat-00107.001"]}
                position={[-0.827, -0.716, 4.803]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00108001"].geometry}
                material={materials["BuildingMat-00108.001"]}
                position={[-0.827, -0.716, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00109001"].geometry}
                material={materials["BuildingMat-00109.001"]}
                position={[-0.826, 1.127, 1.679]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00110001"].geometry}
                material={materials["BuildingMat-00110.001"]}
                position={[-0.826, 1.127, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00112001"].geometry}
                material={materials["BuildingMat-00112.001"]}
                position={[-2.764, -0.716, -3.007]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00115001"].geometry}
                material={materials["BuildingMat-00115.001"]}
                position={[-2.764, -0.716, -4.569]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00116001"].geometry}
                material={materials["BuildingMat-00116.001"]}
                position={[-0.826, 1.127, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00117001"].geometry}
                material={materials["BuildingMat-00117.001"]}
                position={[-0.827, -0.716, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00119001"].geometry}
                material={materials["BuildingMat-00119.001"]}
                position={[1.11, -0.717, 7.927]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00120001"].geometry}
                material={materials["BuildingMat-00120.001"]}
                position={[-2.764, -0.716, -6.13]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00122001"].geometry}
                material={materials["BuildingMat-00122.001"]}
                position={[1.11, -0.717, 6.365]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00123001"].geometry}
                material={materials["BuildingMat-00123.001"]}
                position={[-0.827, -0.716, -1.445]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00124001"].geometry}
                material={materials["BuildingMat-00124.001"]}
                position={[-2.764, -0.717, -7.692]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00126001"].geometry}
                material={materials["BuildingMat-00126.001"]}
                position={[1.11, -0.717, 4.803]}
                rotation={[0, 0, 1.57]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00127001"].geometry}
                material={materials["BuildingMat-00127.001"]}
                position={[1.111, 1.127, 1.679]}
                rotation={[0, 0, 1.57]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00128001"].geometry}
                material={materials["BuildingMat-00128.001"]}
                position={[1.11, -0.716, 3.241]}
                rotation={[0, 0, 1.57]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00130001"].geometry}
                material={materials["BuildingMat-00130.001"]}
                position={[1.111, 1.127, 3.241]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00131001"].geometry}
                material={materials["BuildingMat-00131.001"]}
                position={[1.133, -2.63, -2.795]}
                rotation={[0, 0, 1.571]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00132001"].geometry}
                material={materials["BuildingMat-00132.001"]}
                position={[1.111, 1.126, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00136001"].geometry}
                material={materials["BuildingMat-00136.001"]}
                position={[1.11, -0.716, 0.117]}
                rotation={[0, 0, 1.571]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00138001"].geometry}
                material={materials["BuildingMat-00138.001"]}
                position={[1.133, -2.631, -5.919]}
                rotation={[0, 0, 1.571]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00140001"].geometry}
                material={materials["BuildingMat-00140.001"]}
                position={[5.006, -2.632, 6.577]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00141001"].geometry}
                material={materials["BuildingMat-00141.001"]}
                position={[1.11, -0.717, -1.445]}
                rotation={[0, 0, 1.57]}
                scale={0.008}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00143001"].geometry}
                material={materials["BuildingMat-00143.001"]}
                position={[5.008, 1.054, 3.453]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00144001"].geometry}
                material={materials["BuildingMat-00144.001"]}
                position={[5.007, -2.631, 3.453]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00148001"].geometry}
                material={materials["BuildingMat-00148.001"]}
                position={[5.008, 1.055, 0.328]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00150001"].geometry}
                material={materials["BuildingMat-00150.001"]}
                position={[5.007, -2.631, 0.329]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00153001"].geometry}
                material={materials["BuildingMat-00153.001"]}
                position={[5.006, -2.632, -2.796]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00156001"].geometry}
                material={materials["BuildingMat-00156.001"]}
                position={[5.006, -2.632, -5.92]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00157001"].geometry}
                material={materials["BuildingMat-00157.001"]}
                position={[8.879, -2.633, 6.577]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00159001"].geometry}
                material={materials["BuildingMat-00159.001"]}
                position={[8.88, -2.633, 3.453]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00161"].geometry}
                material={materials["BuildingMat-00161"]}
                position={[8.882, 1.053, 3.453]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00162"].geometry}
                material={materials["BuildingMat-00162"]}
                position={[8.881, 1.053, 0.328]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00163"].geometry}
                material={materials["BuildingMat-00163"]}
                position={[8.88, -2.633, 0.328]}
                rotation={[0, 0, 1.57]}
                scale={0.016}
            />
        </group>
    );
}

useGLTF.preload("/gibraltarNew.glb");


