/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { OrbitControls, PerspectiveCamera, useFBX, useGLTF } from "@react-three/drei";
import dynamic from "next/dynamic";
import { useFrame } from "@react-three/fiber";

const Ship = dynamic(() => import('@/components/canvas/ship').then((mod) => mod.Ship), { ssr: false })

export function Model(props) {
    const { nodes, materials } = useGLTF("/toulon.glb");
    const animationRef = useRef()

    return (
        <group {...props} dispose={null}>
            <ambientLight />
            <PerspectiveCamera makeDefault fov={90} position={[7, 3, 7]} zoom={1} />
            <OrbitControls enableZoom={false} minPolarAngle={0} maxPolarAngle={1.5} />
            <mesh ref={animationRef}><Ship scale={0.4} distances={[0, 20]} position={[-2, -0.08, 0.269]} /></mesh>

            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00002002"].geometry}
                material={materials["BuildingMat-00002.003"]}
                position={[0.332, -0.306, 3.076]}
                rotation={[0, 0.625, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00003002"].geometry}
                material={materials["BuildingMat-00003.003"]}
                position={[2.725, -0.306, 3.086]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00006002"].geometry}
                material={materials["BuildingMat-00006.003"]}
                position={[1.528, -0.306, 3.081]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00007002"].geometry}
                material={materials["BuildingMat-00007.003"]}
                position={[-2.061, -0.306, 3.066]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00008002"].geometry}
                material={materials["BuildingMat-00008.003"]}
                position={[-0.865, -0.306, 3.071]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00009002"].geometry}
                material={materials["BuildingMat-00009.003"]}
                position={[1.118, -0.306, 2.51]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00010002"].geometry}
                material={materials["BuildingMat-00010.003"]}
                position={[1.118, -0.306, 2.51]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00013002"].geometry}
                material={materials["BuildingMat-00013.003"]}
                position={[0.708, -0.306, 1.94]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00014002"].geometry}
                material={materials["BuildingMat-00014.003"]}
                position={[-0.078, -0.306, 2.505]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00015002"].geometry}
                material={materials["BuildingMat-00015.003"]}
                position={[1.904, -0.306, 1.945]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00016002"].geometry}
                material={materials["BuildingMat-00016.003"]}
                position={[1.904, -0.306, 1.945]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00018002"].geometry}
                material={materials["BuildingMat-00018.003"]}
                position={[2.314, -0.306, 2.515]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00019002"].geometry}
                material={materials["BuildingMat-00019.003"]}
                position={[-2.471, -0.306, 2.495]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00022002"].geometry}
                material={materials["BuildingMat-00022.003"]}
                position={[-1.275, -0.306, 2.5]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00023002"].geometry}
                material={materials["BuildingMat-00023.003"]}
                position={[-2.882, -0.305, 1.925]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00024002"].geometry}
                material={materials["BuildingMat-00024.003"]}
                position={[-2.882, -0.305, 1.925]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00025002"].geometry}
                material={materials["BuildingMat-00025.003"]}
                position={[-3.715, -0.288, 2.435]}
                rotation={[0, 0.63, 1.571]}
                scale={0.002}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00026002"].geometry}
                material={materials["BuildingMat-00026.003"]}
                position={[-3.715, -0.288, 2.435]}
                rotation={[0, 0.63, 1.571]}
                scale={0.002}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00027002"].geometry}
                material={materials["BuildingMat-00027.003"]}
                position={[1.494, -0.306, 1.374]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00028002"].geometry}
                material={materials["BuildingMat-00028.003"]}
                position={[0.297, -0.306, 1.369]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00029002"].geometry}
                material={materials["BuildingMat-00029.003"]}
                position={[-3.92, -0.288, 2.15]}
                rotation={[0, 0.612, 1.571]}
                scale={0.002}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00030002"].geometry}
                material={materials["BuildingMat-00030.003"]}
                position={[-3.92, -0.288, 2.15]}
                rotation={[0, 0.612, 1.571]}
                scale={0.002}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00031002"].geometry}
                material={materials["BuildingMat-00031.003"]}
                position={[3.101, -0.306, 1.95]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00032002"].geometry}
                material={materials["BuildingMat-00032.003"]}
                position={[2.69, -0.306, 1.379]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00033002"].geometry}
                material={materials["BuildingMat-00033.003"]}
                position={[2.69, -0.306, 1.379]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00034002"].geometry}
                material={materials["BuildingMat-00034.003"]}
                position={[-1.685, -0.306, 1.93]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00035002"].geometry}
                material={materials["BuildingMat-00035.003"]}
                position={[-0.489, -0.306, 1.935]}
                rotation={[0, 0.625, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00038002"].geometry}
                material={materials["BuildingMat-00038.003"]}
                position={[-3.292, -0.305, 1.355]}
                rotation={[0, 0.621, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00039002"].geometry}
                material={materials["BuildingMat-00039.003"]}
                position={[-3.292, -0.305, 1.355]}
                rotation={[0, 0.621, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00040002"].geometry}
                material={materials["BuildingMat-00040.003"]}
                position={[1.083, -0.306, 0.804]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00042002"].geometry}
                material={materials["BuildingMat-00042.003"]}
                position={[2.28, -0.306, 0.809]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00043002"].geometry}
                material={materials["BuildingMat-00043.003"]}
                position={[-2.096, -0.306, 1.36]}
                rotation={[0, 0.625, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00044002"].geometry}
                material={materials["BuildingMat-00044.003"]}
                position={[-0.899, -0.306, 1.364]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00047002"].geometry}
                material={materials["BuildingMat-00047.003"]}
                position={[-2.506, -0.306, 0.789]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00048002"].geometry}
                material={materials["BuildingMat-00048.003"]}
                position={[-2.506, -0.306, 0.789]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00049002"].geometry}
                material={materials["BuildingMat-00049.003"]}
                position={[-3.703, -0.305, 0.784]}
                rotation={[0, 0.624, Math.PI / 2]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00050002"].geometry}
                material={materials["BuildingMat-00050.003"]}
                position={[-1.72, -0.306, 0.224]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00051002"].geometry}
                material={materials["BuildingMat-00051.003"]}
                position={[-0.113, -0.306, 0.799]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00052002"].geometry}
                material={materials["BuildingMat-00052.003"]}
                position={[3.476, -0.306, 0.814]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00053002"].geometry}
                material={materials["BuildingMat-00053.003"]}
                position={[-1.31, -0.306, 0.794]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00054002"].geometry}
                material={materials["BuildingMat-00054.003"]}
                position={[3.066, -0.306, 0.244]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00055002"].geometry}
                material={materials["BuildingMat-00055.003"]}
                position={[3.066, -0.306, 0.244]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00056002"].geometry}
                material={materials["BuildingMat-00056.003"]}
                position={[1.869, -0.306, 0.238]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00057002"].geometry}
                material={materials["BuildingMat-00057.003"]}
                position={[-2.916, -0.306, 0.219]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00060002"].geometry}
                material={materials["BuildingMat-00060.003"]}
                position={[-4.113, -0.305, 0.214]}
                rotation={[0, 0.624, Math.PI / 2]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00061002"].geometry}
                material={materials["BuildingMat-00061.003"]}
                position={[-4.113, -0.305, 0.214]}
                rotation={[0, 0.624, Math.PI / 2]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00062002"].geometry}
                material={materials["BuildingMat-00062.003"]}
                position={[0.673, -0.306, 0.233]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00063002"].geometry}
                material={materials["BuildingMat-00063.003"]}
                position={[0.673, -0.306, 0.233]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00068002"].geometry}
                material={materials["BuildingMat-00068.003"]}
                position={[2.655, -0.306, -0.327]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00069002"].geometry}
                material={materials["BuildingMat-00069.003"]}
                position={[2.655, -0.306, -0.327]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00070002"].geometry}
                material={materials["BuildingMat-00070.003"]}
                position={[-0.524, -0.306, 0.229]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00071002"].geometry}
                material={materials["BuildingMat-00071.003"]}
                position={[-2.13, -0.306, -0.347]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00072002"].geometry}
                material={materials["BuildingMat-00072.003"]}
                position={[-2.13, -0.306, -0.347]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00073002"].geometry}
                material={materials["BuildingMat-00073.003"]}
                position={[1.459, -0.306, -0.332]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00074002"].geometry}
                material={materials["BuildingMat-00074.003"]}
                position={[1.459, -0.306, -0.332]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00075002"].geometry}
                material={materials["BuildingMat-00075.003"]}
                position={[-3.327, -0.306, -0.352]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00076002"].geometry}
                material={materials["BuildingMat-00076.003"]}
                position={[-3.327, -0.306, -0.352]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00077001"].geometry}
                material={materials["BuildingMat-00077.003"]}
                position={[3.852, -0.306, -0.322]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00082002"].geometry}
                material={materials["BuildingMat-00082.003"]}
                position={[0.263, -0.306, -0.337]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00083002"].geometry}
                material={materials["BuildingMat-00083.003"]}
                position={[-0.934, -0.306, -0.342]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00084001"].geometry}
                material={materials["BuildingMat-00084.003"]}
                position={[2.245, -0.306, -0.897]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00085002"].geometry}
                material={materials["BuildingMat-00085.003"]}
                position={[1.049, -0.306, -0.902]}
                rotation={[0, 0.625, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00086002"].geometry}
                material={materials["BuildingMat-00086.003"]}
                position={[1.049, -0.306, -0.902]}
                rotation={[0, 0.625, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00087002"].geometry}
                material={materials["BuildingMat-00087.003"]}
                position={[1.049, -0.306, -0.902]}
                rotation={[0, 0.625, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00088002"].geometry}
                material={materials["BuildingMat-00088.003"]}
                position={[-2.541, -0.306, -0.917]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00089002"].geometry}
                material={materials["BuildingMat-00089.003"]}
                position={[-2.541, -0.306, -0.917]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00090002"].geometry}
                material={materials["BuildingMat-00090.003"]}
                position={[-1.344, -0.306, -0.912]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00091002"].geometry}
                material={materials["BuildingMat-00091.003"]}
                position={[3.442, -0.306, -0.892]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00097002"].geometry}
                material={materials["BuildingMat-00097.003"]}
                position={[-0.148, -0.306, -0.907]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00098002"].geometry}
                material={materials["BuildingMat-00098.003"]}
                position={[1.835, -0.306, -1.468]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00099002"].geometry}
                material={materials["BuildingMat-00099.003"]}
                position={[1.835, -0.306, -1.468]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00100002"].geometry}
                material={materials["BuildingMat-00100.003"]}
                position={[-2.951, -0.306, -1.488]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00101002"].geometry}
                material={materials["BuildingMat-00101.003"]}
                position={[-1.755, -0.306, -1.483]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00102002"].geometry}
                material={materials["BuildingMat-00102.003"]}
                position={[3.031, -0.306, -1.463]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00103001"].geometry}
                material={materials["BuildingMat-00103.003"]}
                position={[0.638, -0.306, -1.473]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00107002"].geometry}
                material={materials["BuildingMat-00107.003"]}
                position={[-2.165, -0.306, -2.053]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00110002"].geometry}
                material={materials["BuildingMat-00110.003"]}
                position={[-0.558, -0.306, -1.478]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00111002"].geometry}
                material={materials["BuildingMat-00111.003"]}
                position={[1.424, -0.306, -2.038]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00112002"].geometry}
                material={materials["BuildingMat-00112.003"]}
                position={[1.424, -0.306, -2.038]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00114002"].geometry}
                material={materials["BuildingMat-00114.003"]}
                position={[2.621, -0.306, -2.033]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00117001"].geometry}
                material={materials["BuildingMat-00117.003"]}
                position={[0.228, -0.306, -2.043]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00121002"].geometry}
                material={materials["BuildingMat-00121.003"]}
                position={[-0.969, -0.306, -2.048]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00124001"].geometry}
                material={materials["BuildingMat-00124.003"]}
                position={[2.21, -0.306, -2.604]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00125001"].geometry}
                material={materials["BuildingMat-00125.003"]}
                position={[1.014, -0.306, -2.609]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00126001"].geometry}
                material={materials["BuildingMat-00126.003"]}
                position={[1.014, -0.306, -2.609]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00128002"].geometry}
                material={materials["BuildingMat-00128.003"]}
                position={[-0.183, -0.306, -2.614]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00129002"].geometry}
                material={materials["BuildingMat-00129.003"]}
                position={[-0.183, -0.306, -2.614]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00131001"].geometry}
                material={materials["BuildingMat-00131.003"]}
                position={[-1.379, -0.306, -2.619]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00132001"].geometry}
                material={materials["BuildingMat-00132.003"]}
                position={[-2.576, -0.306, -2.624]}
                rotation={[0, 0.623, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00138001"].geometry}
                material={materials["BuildingMat-00138.003"]}
                position={[0.603, -0.306, -3.179]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00139001"].geometry}
                material={materials["BuildingMat-00139.003"]}
                position={[0.603, -0.306, -3.179]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00140001"].geometry}
                material={materials["BuildingMat-00140.003"]}
                position={[-1.79, -0.306, -3.189]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00141001"].geometry}
                material={materials["BuildingMat-00141.003"]}
                position={[-0.593, -0.306, -3.184]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["BuildingMesh-00142001"].geometry}
                material={materials["BuildingMat-00142.003"]}
                position={[-0.593, -0.306, -3.184]}
                rotation={[0, 0.624, 1.571]}
                scale={0.004}
            />
        </group>
    );
}

useGLTF.preload("/toulon.glb");
